name: Minimal usage
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v5.3
    - name: Test CernVM-FS
      run: |
        sudo mkdir -p /Library/Application\ Support/fuse-t/cfg/
        sudo zsh -c 'echo "namedattr=true" >> /Library/Application\ Support/fuse-t/cfg/fuse-t.ini'
        sudo mkdir /cvmfs/sft.cern.ch
        sudo mount -o backend=smb -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
        sleep 1
        ls /cvmfs/sft.cern.ch
        ls /cvmfs/sft.cern.ch/lcg/views//LCG_108/arm64-mac15-clang170-opt/setup.sh
        bash -c "source /cvmfs/sft.cern.ch/lcg/views//LCG_108/arm64-mac15-clang170-opt/setup.sh"
        echo "souce successful"
        bash -c "source /cvmfs/sft.cern.ch/lcg/views//LCG_108/arm64-mac15-clang170-opt/setup.sh; root --version"
        bash -c "source /cvmfs/sft.cern.ch/lcg/views//LCG_108/arm64-mac15-clang170-opt/setup.sh; gaudirun.py -h"
        git clone --depth 1 https://github.com/aidasoft/podio
        cd podio; mkdir build; cd build
        cmake ..
        make -j 4
        make test
