name: Minimal usage
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v5.3
    - name: Test CernVM-FS
      run: |
        sudo mkdir /cvmfs/sft.cern.ch
        sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
        sleep 1
        source /cvmfs/sft.cern.ch/lcg/views//LCG_108/arm64-mac15-clang170-opt/setup.sh
        root --version
        gaudirun.py -h
